#pragma config(Sensor, dgtl1,  RDE,            sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LDE,            sensorQuadEncoder)
#pragma config(Motor,  port2,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LDrive,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "DriverTask.c"
#include "AutonTask.c"
void pre_auton()
{

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.


	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{

	Auton();
}

task usercontrol()
{
  // User control code here, inside the loop
	startTask(PIDRight);
	startTask(PIDLeft);

  while (true)
  {
    //Control();


  }
}
