#pragma config(Sensor, dgtl1,  RDE,            sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LDE,            sensorQuadEncoder)
#pragma config(Motor,  port1,           BallIn,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TopFly,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BotFly,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           TopRDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           TopLDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftTower,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightTower,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LDrive,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "DriverTask.c"
#include "AutonTask.c"
void pre_auton()
{

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.


	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{

	Auton();
}

task usercontrol()
{
  // User control code here, inside the loop
	startTask(PIDRight);
	startTask(PIDLeft);
int mogoLift = 0;
int Tower = 0;
int Ball = 0;
  while (true)
  {
  	if (vexRT[Btn6U] == 1){
			mogoLift = 1;
    motor[TopFly]=127;
    motor[BotFly]=127;
		}
		else{
			mogoLift = 0;
    motor[TopFly]=0;
    motor[BotFly]=0;
		}
		if (vexRT[Btn8U] == 1){
			Tower = 1;
    motor[LeftTower]=127;
    motor[RightTower]=127;
		}
				else if (vexRT[Btn8D] == 1){
			Tower = 1;
    motor[LeftTower]=-127;
    motor[RightTower]=-127;
		}
		else{
			Tower = 0;
    motor[LeftTower]=0;
    motor[RightTower]=0;
		}
 	if (vexRT[Btn5U] == 1){
			Ball = 1;
    motor[BallIn]=127;
		}
		else if (vexRT[Btn5D] == 1){
			Ball = 1;
    motor[BallIn]=-127;
		}
		else{
			Ball = 0;
    motor[BallIn]=0;
		}
  }
}
